/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.time.LocalDate;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.EmployeeProfile;
import model.EnumList;

/**
 *
 * @author Ruolin Li
 */
public class ManageJPanel extends javax.swing.JPanel {
    /**
     * Creates new form ManageJPanel
     */
    HashMap<String,EmployeeProfile> employeeProfileMap;
    EnumList enumList;
    public ManageJPanel(HashMap employeeProfileMap) {
        initComponents();
        this.employeeProfileMap = employeeProfileMap;
        showTable();
    }
    private Object[] addTableRow(Object[] row,EmployeeProfile ep){
        row[0] = ep.getEmployeeId();
        row[1] = ep.getName();
        row[2] = ep.getAge();
        row[3] = ep.getGender();
        row[4] = ep.getStartDate();
        row[5] = ep.getLevel();
        row[6] = ep.getTeamInfo();
        row[7] = ep.getPositionTitle();
        row[8] = ep.getCellPhoneNumber();
        row[9] = ep.getEmailAddress();
        return row;
    }
    private void showTable(){
        DefaultTableModel model = (DefaultTableModel)jTableProfile.getModel();
        model.setRowCount(0);
        EmployeeProfile ep = new EmployeeProfile();
        for(String key : employeeProfileMap.keySet()){
            ep = employeeProfileMap.get(key);
            Object[] row = new Object[10];
            addTableRow(row,ep);
            
            model.addRow(row);     
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProfile = new javax.swing.JTable();
        jButtonView = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextTeamInfo = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextStartDate = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextPhoneNum = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextName = new javax.swing.JTextField();
        jTextEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextLevel = new javax.swing.JTextField();
        jTextTitle = new javax.swing.JTextField();
        jButtonUpdate = new javax.swing.JButton();
        jTextAge = new javax.swing.JTextField();
        Photo = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jTextGender = new javax.swing.JTextField();
        jTextSid = new javax.swing.JTextField();
        jTextSname = new javax.swing.JTextField();
        jButtonId = new javax.swing.JButton();
        jButtonName = new javax.swing.JButton();
        jButtonGender = new javax.swing.JButton();
        jButtonLevel = new javax.swing.JButton();
        jButtonTitle = new javax.swing.JButton();
        jComboBoxGender = new javax.swing.JComboBox<EnumList.GenderEnum>();
        jComboBoxLevel = new javax.swing.JComboBox<EnumList.LevelEnum>();
        jComboBoxTitle = new javax.swing.JComboBox<>();
        jTextSage = new javax.swing.JTextField();
        jButtonAge = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1220, 900));
        setMinimumSize(new java.awt.Dimension(1220, 900));
        setPreferredSize(new java.awt.Dimension(1220, 900));

        jTableProfile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Age", "Gender", "Start Date", "Level", "Team Info", "Title", "Phone Number", "Email "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableProfile);

        jButtonView.setBackground(new java.awt.Color(238, 238, 238));
        jButtonView.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jButtonView.setText("View");
        jButtonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewActionPerformed(evt);
            }
        });

        jButtonDelete.setBackground(new java.awt.Color(238, 238, 238));
        jButtonDelete.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jTextTeamInfo.setColumns(20);
        jTextTeamInfo.setRows(5);
        jScrollPane4.setViewportView(jTextTeamInfo);

        jLabel15.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel15.setText("Photo");

        jLabel6.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel6.setText("Start Date");

        try {
            jFormattedTextStartDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel7.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel7.setText("PositionTitle");

        try {
            jFormattedTextPhoneNum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel8.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel8.setText("Level");

        jLabel10.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel10.setText("Email Address");

        jLabel12.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel12.setText("CellPhone Number");

        jLabel2.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel3.setText("EmployeeId");

        jLabel4.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel4.setText("Gender");

        jLabel5.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel5.setText("Age");

        jLabel14.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel14.setText("Team Info ");

        jButtonUpdate.setBackground(new java.awt.Color(238, 238, 238));
        jButtonUpdate.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonId.setText("Search ID");
        jButtonId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIdActionPerformed(evt);
            }
        });

        jButtonName.setText("Search Name");
        jButtonName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNameActionPerformed(evt);
            }
        });

        jButtonGender.setText("SearchGender");
        jButtonGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenderActionPerformed(evt);
            }
        });

        jButtonLevel.setText("Search Level");
        jButtonLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLevelActionPerformed(evt);
            }
        });

        jButtonTitle.setText("Search Title");
        jButtonTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTitleActionPerformed(evt);
            }
        });

        jComboBoxGender.setModel(new javax.swing.DefaultComboBoxModel<>(EnumList.GenderEnum.values()));

        jComboBoxLevel.setModel(new javax.swing.DefaultComboBoxModel<>(EnumList.LevelEnum.values()));

        jComboBoxTitle.setModel(new javax.swing.DefaultComboBoxModel<>(EnumList.TitleEnum.values()));

        jButtonAge.setText("SearchAge");
        jButtonAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                    .addComponent(jTextName)
                    .addComponent(jFormattedTextStartDate)
                    .addComponent(jTextLevel)
                    .addComponent(jTextAge)
                    .addComponent(jLabelId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextGender))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(524, 524, 524)
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonView, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextTitle)
                                    .addComponent(jFormattedTextPhoneNum, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Photo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 4, Short.MAX_VALUE)
                                        .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jTextSid, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonName)
                        .addGap(2, 2, 2)
                        .addComponent(jButtonAge, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonGender))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextSname, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jTextSage, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxTitle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextSage)
                    .addComponent(jTextSid, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jTextSname)
                    .addComponent(jComboBoxGender)
                    .addComponent(jComboBoxTitle)
                    .addComponent(jComboBoxLevel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButtonAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonView, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jLabelId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextName, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jTextAge))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jTextGender))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jFormattedTextStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jTextTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jFormattedTextPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Photo, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(103, 103, 103))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(125, 125, 125)))))
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        int selectedIndex = jTableProfile.getSelectedRow();
        if(selectedIndex < 0){
            JOptionPane.showMessageDialog(this,"Please select a row to delete");
            return;
        }
        DefaultTableModel model = (DefaultTableModel)jTableProfile.getModel();
        String employeeId = model.getValueAt(selectedIndex,0).toString();
        employeeProfileMap.remove(employeeId);
        
        JOptionPane.showMessageDialog(this,"Employee Profile of "+employeeId+" deleted");
        
        showTable();
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewActionPerformed
        // TODO add your handling code here:
        int selectedIndex = jTableProfile.getSelectedRow();
        if(selectedIndex < 0){
            JOptionPane.showMessageDialog(this,"Please select a row to view");
            return;
        }
        DefaultTableModel model = (DefaultTableModel)jTableProfile.getModel();
        String employeeId = model.getValueAt(selectedIndex, 0).toString();
        EmployeeProfile ep = employeeProfileMap.get(employeeId);
        
        jLabelId.setText(ep.getEmployeeId());
        jTextName.setText(ep.getName());
        jTextAge.setText(ep.getAge()+"");
        jTextGender.setText(ep.getGender());
        jTextEmail.setText(ep.getEmailAddress());
        jTextLevel.setText(ep.getLevel());
        jTextTeamInfo.setText(ep.getTeamInfo());
        jTextTitle.setText(ep.getPositionTitle());
        jFormattedTextPhoneNum.setText(ep.getCellPhoneNumber());
        jFormattedTextStartDate.setText(ep.getStartDate().toString());
        Photo.setIcon(ep.getPhoto());
        
    }//GEN-LAST:event_jButtonViewActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        String employeeId = jLabelId.getText();
        EmployeeProfile ep = new EmployeeProfile();
        ep.setEmployeeId(employeeId);
        ep.setAge(Integer.parseInt(jTextAge.getText()));
        ep.setName(jTextName.getText());
        ep.setGender(jTextGender.getText());
        ep.setCellPhoneNumber(jFormattedTextPhoneNum.getText());
        ep.setEmailAddress(jTextEmail.getText());
        ep.setLevel(jTextLevel.getText());
        ep.setPositionTitle(jTextTitle.getText());
        ep.setStartDate(LocalDate.parse(jFormattedTextStartDate.getText()));
        ep.setTeamInfo(jTextTeamInfo.getText());
        ep.setPhoto(null);

        employeeProfileMap.put(employeeId,ep);
        
        JOptionPane.showMessageDialog(this,"Employee Profile of "+employeeId+" updated");
        showTable();
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIdActionPerformed
        // TODO add your handling code here:
        //https://blog.csdn.net/gjs935219/article/details/97396294
        String filter = jTextSid.getText().trim();
        DefaultTableModel model = (DefaultTableModel)jTableProfile.getModel();
        model.setRowCount(0);
        for(String key : employeeProfileMap.keySet()){
            EmployeeProfile ep = employeeProfileMap.get(key);
            if(ep.getEmployeeId().equals(filter)){
                Object[] row = new Object[10];
                addTableRow(row,ep);
                
                model.addRow(row);
            }
	}
        if(model.getRowCount()>0){
            jTextSid.setText("");
        }

    }//GEN-LAST:event_jButtonIdActionPerformed

    private void jButtonNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNameActionPerformed
        // TODO add your handling code here:
        String filter = jTextSname.getText().trim();
        DefaultTableModel model = (DefaultTableModel)jTableProfile.getModel();
        model.setRowCount(0);
        for(String key : employeeProfileMap.keySet()){
            EmployeeProfile ep = employeeProfileMap.get(key);
            if(ep.getName().equals(filter)){
                Object[] row = new Object[10];
                addTableRow(row,ep);
                
                model.addRow(row);
            }
	}
        if(model.getRowCount()>0){
            jTextSname.setText("");
        }
    }//GEN-LAST:event_jButtonNameActionPerformed

    private void jButtonGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenderActionPerformed
        // TODO add your handling code here:
        String filter = jComboBoxGender.getSelectedItem().toString();
        DefaultTableModel model = (DefaultTableModel)jTableProfile.getModel();
        model.setRowCount(0);
        for(String key : employeeProfileMap.keySet()){
            EmployeeProfile ep = employeeProfileMap.get(key);
            if(ep.getGender().equals(filter)){
                Object[] row = new Object[10];
                addTableRow(row,ep);
                
                model.addRow(row);
            }	
	}
    }//GEN-LAST:event_jButtonGenderActionPerformed

    private void jButtonLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLevelActionPerformed
        // TODO add your handling code here:
        String filter = jComboBoxLevel.getSelectedItem().toString();
        DefaultTableModel model = (DefaultTableModel)jTableProfile.getModel();
        model.setRowCount(0);
        for(String key : employeeProfileMap.keySet()){
            EmployeeProfile ep = employeeProfileMap.get(key);
            if(ep.getLevel().equals(filter)){
                Object[] row = new Object[10];
                addTableRow(row,ep);
                
                model.addRow(row);
            }
	}
    }//GEN-LAST:event_jButtonLevelActionPerformed

    private void jButtonTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTitleActionPerformed
        // TODO add your handling code here:
        String filter = jComboBoxTitle.getSelectedItem().toString();
        DefaultTableModel model = (DefaultTableModel)jTableProfile.getModel();
        model.setRowCount(0);
        for(String key : employeeProfileMap.keySet()){
            EmployeeProfile ep = employeeProfileMap.get(key);
            if(ep.getPositionTitle().equals(filter)){
                Object[] row = new Object[10];
                addTableRow(row,ep);
                
                model.addRow(row);
            }
	}
    }//GEN-LAST:event_jButtonTitleActionPerformed

    private void jButtonAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgeActionPerformed
        // TODO add your handling code here:
        int filter = Integer.parseInt(jTextSname.getText().trim());
        DefaultTableModel model = (DefaultTableModel)jTableProfile.getModel();
        model.setRowCount(0);
        for(String key : employeeProfileMap.keySet()){
            EmployeeProfile ep = employeeProfileMap.get(key);
            if(ep.getAge()==filter){
                Object[] row = new Object[10];
                addTableRow(row,ep);
                
                model.addRow(row);
            }
	}
        if(model.getRowCount()>0){
            jTextSname.setText("");
        }
    }//GEN-LAST:event_jButtonAgeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Photo;
    private javax.swing.JButton jButtonAge;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonGender;
    private javax.swing.JButton jButtonId;
    private javax.swing.JButton jButtonLevel;
    private javax.swing.JButton jButtonName;
    private javax.swing.JButton jButtonTitle;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JButton jButtonView;
    private javax.swing.JComboBox<EnumList.GenderEnum> jComboBoxGender;
    private javax.swing.JComboBox<EnumList.LevelEnum> jComboBoxLevel;
    private javax.swing.JComboBox<EnumList.TitleEnum> jComboBoxTitle;
    private javax.swing.JFormattedTextField jFormattedTextPhoneNum;
    private javax.swing.JFormattedTextField jFormattedTextStartDate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableProfile;
    private javax.swing.JTextField jTextAge;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextGender;
    private javax.swing.JTextField jTextLevel;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTextField jTextSage;
    private javax.swing.JTextField jTextSid;
    private javax.swing.JTextField jTextSname;
    private javax.swing.JTextArea jTextTeamInfo;
    private javax.swing.JTextField jTextTitle;
    // End of variables declaration//GEN-END:variables
}
